from llm import llm
from prompts.system_prompt import SYSTEM_PROMPT
from tools.report_tool import (
    search_report,
    generate_report,
    generate_executive_summary
)


def report_agent(user_query):
    """
    Handles report-related requests.
    """

    query = user_query.lower()

    # ---------------------------------
    # Executive Summary
    # ---------------------------------
    if "executive" in query or "summary" in query:

        summary = generate_executive_summary()

        prompt = f"""
{SYSTEM_PROMPT}

Executive Summary Data:

{summary}

Generate a professional executive summary.

Include:
- Total Reports
- Generated By
- Date
- Security Recommendation
"""

        response = llm.invoke(prompt)

        return response.content

    # ---------------------------------
    # Generate Investigation Report
    # ---------------------------------
    elif "generate" in query or "create" in query:

        incident_id = None

        for word in user_query.split():

            if word.upper().startswith("INC"):
                incident_id = word.upper()
                break

        if not incident_id:
            incident_id = "INC0001"

        report = generate_report(
            incident_id,
            "Investigation completed successfully."
        )

        prompt = f"""
{SYSTEM_PROMPT}

New Investigation Report

{report}

Generate a professional report confirmation.

Include:
- Report ID
- Incident ID
- Summary
- Date
"""

        response = llm.invoke(prompt)

        return response.content

    # ---------------------------------
    # Search Reports
    # ---------------------------------
    else:

        reports = search_report()

        if not reports:
            return "No reports available."

        prompt = f"""
{SYSTEM_PROMPT}

User Request:
{user_query}

Reports:
{reports[:10]}

Generate a concise report summary.

Include:
- Number of reports
- Incident IDs
- Key findings
"""

        response = llm.invoke(prompt)

        return response.content